import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
const UI = await import('@ivy-interactive/components/ui');
const h = React.createElement;
const out = {};
function reg(name, fn){ try { out[name]=renderToStaticMarkup(fn()); } catch(e){ out[name]='ERROR: '+e.message; } }

reg('DropdownMenuItem', ()=>h(UI.DropdownMenu,{open:true},h(UI.DropdownMenuTrigger,null,'t'),h(UI.DropdownMenuContent,null,h(UI.DropdownMenuItem,null,'item'))));
reg('AlertDialog', ()=>h(UI.AlertDialog,{open:true},h(UI.AlertDialogContent,null,h(UI.AlertDialogFooter,null,h(UI.AlertDialogCancel,null,'Cancel'),h(UI.AlertDialogAction,null,'OK')))));
reg('Popover trigger', ()=>h(UI.Popover,null,h(UI.PopoverTrigger,null,'open')));
reg('Command', ()=>h(UI.Command,null,h(UI.CommandInput,{placeholder:'s'}),h(UI.CommandList,null,h(UI.CommandItem,null,'ci'))));
reg('Toast close', ()=>h(UI.ToastProvider,null,h(UI.Toast,{open:true},h(UI.ToastTitle,null,'T'),h(UI.ToastClose,null))));
reg('Menubar', ()=>h(UI.Menubar,null,h(UI.MenubarMenu,null,h(UI.MenubarTrigger,null,'File'))));
reg('ContextMenu trigger', ()=>h(UI.ContextMenu,null,h(UI.ContextMenuTrigger,null,'right click')));
reg('Stepper', ()=>h(UI.Stepper,{orientation:'horizontal'},h(UI.StepperItem,{step:1},h(UI.StepperTrigger,null,h(UI.StepperIndicator,null,'1')))));
reg('Sheet', ()=>h(UI.Sheet,{open:true},h(UI.SheetContent,null,h(UI.SheetTitle,null,'T'))));
reg('Dialog', ()=>h(UI.Dialog,{open:true},h(UI.DialogContent,null,h(UI.DialogTitle,null,'T'))));
reg('Collapsible trigger', ()=>h(UI.Collapsible,null,h(UI.CollapsibleTrigger,null,'more')));
reg('Label', ()=>h(UI.Label,{htmlFor:'x'},'lbl'));
reg('Input', ()=>h(UI.Input,{}));
reg('Textarea', ()=>h(UI.Textarea,{}));
reg('Progress', ()=>h(UI.Progress,{value:50}));
reg('Avatar', ()=>h(UI.Avatar,null,h(UI.AvatarFallback,null,'AB')));
reg('Skeleton', ()=>h(UI.Skeleton,{className:'h-4 w-10'}));
reg('Spinner', ()=>h(UI.Spinner,null));
reg('Multiselect', ()=>h(UI.MultiSelect ?? UI.Multiselect ?? 'div',{options:[{label:'a',value:'a'}]}));
reg('DataTable', ()=>h(UI.DataTable,{columns:[{accessorKey:'a',header:'A'}],data:[{a:1}]}));
reg('Alert', ()=>h(UI.Alert,null,'x'));
reg('Accordion', ()=>h(UI.Accordion,{type:'single'},h(UI.AccordionItem,{value:'v',disabled:true},h(UI.AccordionTrigger,null,'T'),h(UI.AccordionContent,null,'C'))));
reg('Tabs disabled trigger', ()=>h(UI.Tabs,{defaultValue:'a'},h(UI.TabsList,null,h(UI.TabsTrigger,{value:'b',disabled:true},'B'))));
reg('Checkbox disabled', ()=>h(UI.Checkbox,{disabled:true}));
reg('Switch disabled', ()=>h(UI.Switch,{disabled:true}));
reg('Select disabled', ()=>h(UI.Select,{disabled:true},h(UI.SelectTrigger,null,h(UI.SelectValue,{placeholder:'p'}))));
reg('Card disabled', ()=>h(UI.Card,{disabled:true},h('p',null,'body text')));
reg('Toolbar', ()=>h(UI.Toolbar,{'aria-label':'tb'},h(UI.ToolbarButton ?? 'button',null,'b')));
reg('Slider disabled', ()=>h(UI.Slider,{disabled:true,defaultValue:[1]}));
reg('StatusLine', ()=>h(UI.StatusLine,{status:'ok',children:'s'}));
reg('Pagination', ()=>h(UI.Pagination,null,h(UI.PaginationContent,null,h(UI.PaginationItem,null,h(UI.PaginationPrevious,{href:'#'})))));
console.log(JSON.stringify(out,null,1));
