//! Recreates a project's environment files inside a plan's worktree.
//!
//! A git worktree is a clean checkout, so the untracked `.env` files the original repo relies on are
//! absent and services and database migrations fail to boot. Each [`ProjectEnvFileConfig`] is
//! rebuilt from its template plus overrides, with placeholders resolved against the plan's allocated
//! ports so inter-service URLs (`VITE_API_URL`, `DB_SERVICE_URL`) point at the right ports.

use crate::config::{expand_variables, get_config_path, load_config};
use crate::error::{Result, TendrilError};
use crate::git::worktree::derive_worktree_relative_path;
use crate::models::{PlanYaml, ProjectConfig, ProjectEnvFileConfig, ProjectPortConfig};
use crate::plans::ports::allocate_ports;
use crate::plans::reader::read_plan_yaml;
use regex::Regex;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::LazyLock;

/// `${ports.<name>}` — the port assigned to a named service.
static PORT_PLACEHOLDER: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\$\{ports\.([A-Za-z0-9_.-]+)\}").unwrap());

/// `${env.<VAR>}` — a host environment variable.
static ENV_PLACEHOLDER: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\$\{env\.([A-Za-z_][A-Za-z0-9_]*)\}").unwrap());

/// A `KEY=VALUE` line, optionally prefixed with `export `.
static ENV_ASSIGNMENT: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$").unwrap());

/// First line of a generated env file, identifying it as one Tendril owns.
pub const GENERATED_HEADER: &str = "# Generated by tendril plan env materialize - regenerate with: tendril plan env materialize <plan-id>";

/// Second line of a generated env file, carrying the checksum of the body that follows.
const CHECKSUM_PREFIX: &str = "# tendril-env-checksum: ";

/// A reference an env file could not resolve, e.g. `VITE_TOKEN` ← `${env.API_TOKEN}`. Never
/// substituted with a fabricated value: a plausible-looking fake secret is worse than an empty one.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MissingValue {
    pub key: String,
    pub reference: String,
}

/// One env file as it would be written, without touching disk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderedEnvFile {
    /// Target path, relative to the worktree root.
    pub path: String,
    /// The rendered body (no generated header), `\n`-joined with a trailing newline.
    pub content: String,
    /// `KEY`/`VALUE` pairs in file order.
    pub values: Vec<(String, String)>,
    /// References that could not be resolved.
    pub missing: Vec<MissingValue>,
}

/// What [`materialize_env_files`] did with one target file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MaterializeOutcome {
    Written,
    Unchanged,
    /// The file on disk is not the one we generated, so it was left alone.
    SkippedHandEdited,
}

impl MaterializeOutcome {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Written => "written",
            Self::Unchanged => "unchanged",
            Self::SkippedHandEdited => "skippedHandEdited",
        }
    }
}

/// The env files materialized into one worktree.
#[derive(Debug, Clone)]
pub struct MaterializedWorktree {
    pub worktree: PathBuf,
    pub files: Vec<(RenderedEnvFile, MaterializeOutcome)>,
}

/// What a full `plan env materialize` run produced.
#[derive(Debug, Clone)]
pub struct PlanEnvReport {
    pub project: String,
    pub allocated_ports: BTreeMap<String, u16>,
    pub worktrees: Vec<MaterializedWorktree>,
}

/// Renders one env file: the template's lines with placeholders expanded (comments and blank lines
/// preserved), then `overrides` applied — replacing a key the template already defines in place,
/// appending the rest in config order.
pub fn render_env_file(
    env_file: &ProjectEnvFileConfig,
    project: &ProjectConfig,
    allocated: &BTreeMap<String, u16>,
    worktree_root: &Path,
    tendril_home: &Path,
) -> RenderedEnvFile {
    let home = tendril_home.to_string_lossy().to_string();
    let mut lines: Vec<String> = Vec::new();
    let mut values: Vec<(String, String)> = Vec::new();
    let mut missing: Vec<MissingValue> = Vec::new();
    // key -> (index into lines, index into values)
    let mut key_index: BTreeMap<String, (usize, usize)> = BTreeMap::new();

    if let Some(template) = env_file
        .template
        .as_deref()
        .filter(|t| !t.trim().is_empty())
    {
        let template_path = worktree_root.join(template);
        // A missing template is not an error: the file is then built from overrides alone.
        if let Ok(raw) = std::fs::read_to_string(&template_path) {
            for raw_line in raw.lines() {
                let Some(caps) = ENV_ASSIGNMENT.captures(raw_line.trim()) else {
                    lines.push(raw_line.to_string());
                    continue;
                };

                let key = caps[1].to_string();
                let (value, unresolved) =
                    expand_value(caps[2].trim(), allocated, &project.ports, &home);
                record_missing(&mut missing, &key, unresolved);

                key_index.insert(key.clone(), (lines.len(), values.len()));
                lines.push(format!("{}={}", key, value));
                values.push((key, value));
            }
        }
    }

    for (key, raw_value) in &env_file.overrides {
        let (value, unresolved) = expand_value(raw_value, allocated, &project.ports, &home);
        record_missing(&mut missing, key, unresolved);
        let line = format!("{}={}", key, value);

        match key_index.get(key) {
            Some(&(line_idx, value_idx)) => {
                lines[line_idx] = line;
                values[value_idx] = (key.clone(), value);
            }
            None => {
                key_index.insert(key.clone(), (lines.len(), values.len()));
                lines.push(line);
                values.push((key.clone(), value));
            }
        }
    }

    // Joined with "\n" unconditionally: dotenv parsers in Node and Python treat a trailing CR as
    // part of the value, which silently corrupts URLs and ports.
    let content = if lines.is_empty() {
        String::new()
    } else {
        format!("{}\n", lines.join("\n"))
    };

    RenderedEnvFile {
        path: env_file.path.clone(),
        content,
        values,
        missing,
    }
}

/// Writes every env file the project configures into `worktree_root`, reporting per file what
/// happened. A file that does not carry our header with a matching checksum was touched by a human
/// and is left alone unless `force` is set.
pub fn materialize_env_files(
    project: &ProjectConfig,
    allocated: &BTreeMap<String, u16>,
    worktree_root: &Path,
    tendril_home: &Path,
    force: bool,
) -> Result<Vec<(RenderedEnvFile, MaterializeOutcome)>> {
    let mut results = Vec::new();

    for env_file in &project.env_files {
        if env_file.path.trim().is_empty() {
            continue;
        }

        let rendered = render_env_file(env_file, project, allocated, worktree_root, tendril_home);
        let target = worktree_root.join(&env_file.path);
        let outcome = decide_outcome(&target, &rendered.content, force);

        if outcome != MaterializeOutcome::SkippedHandEdited
            && outcome != MaterializeOutcome::Unchanged
        {
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&target, generated_file(&rendered.content))?;
        }

        results.push((rendered, outcome));
    }

    Ok(results)
}

/// Allocates the plan's ports and materializes the project's env files into its worktrees.
///
/// This is the single entry point the worktree-creation path calls after `git worktree add`, so a
/// fresh worktree always has its `.env` files and its own ports. A failure here should be logged and
/// tolerated by that caller rather than failing worktree creation.
pub fn materialize_plan_env(
    plan_folder: &Path,
    tendril_home: &Path,
    repo_filter: Option<&str>,
    force: bool,
) -> Result<PlanEnvReport> {
    let (mut plan, _) = read_plan_yaml(plan_folder)?;
    let project = resolve_plan_project(&plan.project, tendril_home)?;
    let allocated_ports = allocate_ports(&project, &mut plan, plan_folder)?;

    let mut worktrees = Vec::new();
    for worktree in resolve_worktrees(&plan, plan_folder, repo_filter) {
        let files =
            materialize_env_files(&project, &allocated_ports, &worktree, tendril_home, force)?;
        worktrees.push(MaterializedWorktree { worktree, files });
    }

    Ok(PlanEnvReport {
        project: project.name,
        allocated_ports,
        worktrees,
    })
}

/// The plan's project config, or an error naming the configured projects.
pub fn resolve_plan_project(project_name: &str, tendril_home: &Path) -> Result<ProjectConfig> {
    let settings = load_config(&get_config_path(tendril_home))?;
    settings
        .projects
        .iter()
        .find(|p| p.name.eq_ignore_ascii_case(project_name))
        .cloned()
        .ok_or_else(|| {
            let names: Vec<&str> = settings.projects.iter().map(|p| p.name.as_str()).collect();
            TendrilError::ProjectNotFound(format!(
                "{} (configured projects: {})",
                project_name,
                if names.is_empty() {
                    "none".to_string()
                } else {
                    names.join(", ")
                }
            ))
        })
}

/// Where a repo's worktree lives for this plan. Reuses the same layout as worktree creation so the
/// two can never drift apart.
pub fn worktree_path(plan_folder: &Path, repo_path: &Path) -> PathBuf {
    plan_folder
        .join("Worktrees")
        .join(derive_worktree_relative_path(repo_path))
}

/// The plan's worktree directories that exist on disk, filtered to `repo_filter` when given
/// (matched against the full repo path or its last segment). A repo whose worktree has not been
/// created is skipped rather than reported: a plan commonly lists repos it never checked out.
pub fn resolve_worktrees(
    plan: &PlanYaml,
    plan_folder: &Path,
    repo_filter: Option<&str>,
) -> Vec<PathBuf> {
    plan.repos
        .iter()
        .filter(|repo| repo_filter.is_none_or(|filter| matches_repo(repo, filter)))
        .map(|repo| worktree_path(plan_folder, Path::new(repo)))
        .filter(|worktree| worktree.is_dir())
        .collect()
}

fn matches_repo(repo_path: &str, filter: &str) -> bool {
    if repo_path.eq_ignore_ascii_case(filter) {
        return true;
    }

    let name = |p: &str| {
        Path::new(p.trim_end_matches(['/', '\\']))
            .file_name()
            .map(|n| n.to_string_lossy().to_string())
            .unwrap_or_default()
    };

    let repo_name = name(repo_path);
    !repo_name.is_empty() && repo_name.eq_ignore_ascii_case(&name(filter))
}

/// Resolves `${ports.<name>}`, `${env.<VAR>}` and `%TENDRIL_HOME%` / `~` in one value, returning it
/// alongside every reference that could not be resolved.
fn expand_value(
    value: &str,
    allocated: &BTreeMap<String, u16>,
    port_defaults: &BTreeMap<String, ProjectPortConfig>,
    tendril_home: &str,
) -> (String, Vec<String>) {
    if value.is_empty() {
        return (String::new(), Vec::new());
    }

    let mut unresolved = Vec::new();

    // An unknown port name is left as written so the misconfiguration is visible in the file.
    let with_ports = PORT_PLACEHOLDER.replace_all(value, |caps: &regex::Captures| {
        let name = &caps[1];
        if let Some(port) = allocated.get(name) {
            return port.to_string();
        }
        match port_defaults.get(name) {
            Some(config) if config.default_port > 0 => config.default_port.to_string(),
            _ => {
                unresolved.push(caps[0].to_string());
                caps[0].to_string()
            }
        }
    });

    // An unset host variable yields an empty value, never a fabricated one.
    let with_env = ENV_PLACEHOLDER.replace_all(&with_ports, |caps: &regex::Captures| {
        match std::env::var(&caps[1]) {
            Ok(v) => v,
            Err(_) => {
                unresolved.push(caps[0].to_string());
                String::new()
            }
        }
    });

    // `expand_variables` does no slash normalization, which would otherwise rewrite the separators
    // of URLs and Windows paths held in env values.
    (expand_variables(&with_env, tendril_home), unresolved)
}

fn record_missing(missing: &mut Vec<MissingValue>, key: &str, unresolved: Vec<String>) {
    for reference in unresolved {
        missing.push(MissingValue {
            key: key.to_string(),
            reference,
        });
    }
}

/// The bytes written for a rendered body: the two-line generated header, then the body.
fn generated_file(body: &str) -> String {
    format!(
        "{}\n{}{:016x}\n{}",
        GENERATED_HEADER,
        CHECKSUM_PREFIX,
        fnv1a_64(body),
        body
    )
}

/// Splits a file we may have generated into its recorded checksum and the body that follows.
fn split_generated(existing: &str) -> Option<(&str, &str)> {
    let (header, rest) = existing.split_once('\n')?;
    if header.trim_end() != GENERATED_HEADER {
        return None;
    }
    let (checksum_line, body) = rest.split_once('\n')?;
    let checksum = checksum_line.trim_end().strip_prefix(CHECKSUM_PREFIX)?;
    Some((checksum, body))
}

fn decide_outcome(target: &Path, body: &str, force: bool) -> MaterializeOutcome {
    if force {
        return MaterializeOutcome::Written;
    }

    let Ok(existing) = std::fs::read_to_string(target) else {
        return MaterializeOutcome::Written;
    };

    // No header, or a checksum that does not match its body: a human owns this file now.
    let Some((checksum, existing_body)) = split_generated(&existing) else {
        return MaterializeOutcome::SkippedHandEdited;
    };
    if checksum != format!("{:016x}", fnv1a_64(existing_body)) {
        return MaterializeOutcome::SkippedHandEdited;
    }

    if existing_body == body {
        MaterializeOutcome::Unchanged
    } else {
        MaterializeOutcome::Written
    }
}

/// FNV-1a over the file body. Deliberately not a crypto hash (nothing here is a security boundary)
/// and deliberately not `DefaultHasher`, whose output is not guaranteed stable across Rust versions.
fn fnv1a_64(data: &str) -> u64 {
    const OFFSET_BASIS: u64 = 0xcbf29ce484222325;
    const PRIME: u64 = 0x100000001b3;

    let mut hash = OFFSET_BASIS;
    for byte in data.as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(PRIME);
    }
    hash
}
